[package]
name = "libzkp"
version = "0.1.0"
edition = "2021"

[lib]
name = "libzkp"
crate-type = ["cdylib"]

[dependencies]
bulletproofs = "5.0"
curve25519-dalek = { version = "4", features = ["serde"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py312"] }
merlin = "3.0"
sha2 = "0.10"
hex = "0.4"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
criterion = "0.5"

[[bench]]
name = "zkp_benchmarks"
harness = false